# Generated by Django 5.0.1 on 2024-01-04 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="subject",
            new_name="Titulo",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="descripcion",
        ),
        migrations.AddField(
            model_name="task",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="tarea_completada",
            field=models.BooleanField(default=True),
        ),
    ]
