# Generated by Django 5.0.1 on 2024-01-04 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_titulo_task_titulo_remove_task_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="descripcion",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="titulo",
            new_name="subject",
        ),
    ]
